### PR TITLE
Proof-reading of the Introduction paragraph

### PR DESCRIPTION
**Pull request by PBSJ**
Proof-reading and tidying up the Introduction paragraph. Mainly grammatical fine-tuning.

I didn't see the need to talk about specific challenges and technical details in the introduction paragraph so removed them for brevity and clarity - hope you don't feel I was too ruthless :-)

Will continue proof-reading further paragraphs as I find the time.

### CODE REVIEW

**Comment by igormcoelho** [comment]
thanks for the contribution, we will analyse it step by step, to guarantee everything is fine.

**Comment by PBSJ** [comment]
Great, thanks Igor - awesome work with this paper by the way :-)

**Comment by vncoelho** [comment]
Hi @PBSJ, thanks for the contribution.

Please take a look at the adaptions that were done.
@igormcoelho, check if they are good.

I tried to maintain the technical information which mentions important key aspects that are noteworthy to be highlighted.

**Comment by igormcoelho** [comment]
Very good @vncoelho , thanks for preserving the original citations. @PBSJ thanks for the contribution, let's try to work always expanding content and fixing typos.

**Pull request merged**
