### PR TITLE
Attempt to clarify Intro paragraph #2

### PR DESCRIPTION
**Pull request by PBSJ**
Thanks for contributing to Community Yellow Paper! We are currently focused in quickly expanding technical content, in order to cover all proposed sections of the document. However, other contributions may also be accepted.

Please mark the intention of this PR:
- [ ] Expanding technical content
- [ ] Fixing typo
- [x] Clarifying confusing/misleading sentences
- [ ] Other

===============================================
Please briefly explain the proposed changes:

I've tried to preserve the original content but make it a little more digestible by breaking down big sentences into a couple of smaller ones.

### CODE REVIEW

**Comment by PBSJ** [comment]
Additionally I tried to enter a bit of whitespace to improve readability. I couldn't see it appear in the preview so I may be missing something in markdown for how to enter whitespace?

**Comment by vncoelho** [comment]
Eabueahuea, no, remove these white space, this is not good :dancer: 
Too much paragraphs, I will check this here.

**Comment by vncoelho** [comment]
@PBSJ, I adjusted the paragraph once more.
It almost got me...There were some adjustments that changed the real meaning we would like to pass. :+1:  hauehauaeea

Let's be careful with the changes.

Thanks for the contributions. I tried to keep the core of your modifications.

**Comment by vncoelho** [comment]
Take another look before we merge this.

**Comment by PBSJ** [comment]
Hahah we are going back on forth on this eh @vncoelho  :-)

Hmm, so yes I definitely do not want to change the intent of the message you are trying to convey. 

My only desire here is to make it easier to understand for an English reader. 

I fully appreciate that English is not everyone's first language (it is my first language but I suck at almost every other language!). 

However there are a few grammatical anomalies which make understanding the message quite hard for me as a native English speaker. 

For example this phrase 'it is noteworthy that SC's transactions persisting... pose a unique set of challenges' isn't very easy to read - as I understand it you mean to say 'it's worth noting that persisting SC transactions... poses a unique set of challenges' - in other words, the difficult thing is to be able to persist the Smart Contract's transactions. Is that correct?

So, I'm just wondering what is the best way to proceed - because I feel a bit bad if I'm constantly correcting English etc, but on the other hand I was hoping to make it easier to read. 

But the two things I don't want to do are:
- Change the intent of the message
- Insult the author ;-)

**Comment by igormcoelho** [comment]
let's keep going @PBSJ , you're doing a nice job... and Vitor as well, for handling these revisions so quickly... I can also contribute in the PR process, but I'll take longer to respond. Anyway, in short-term this document will be so much better, congratulations.

**Comment by PBSJ** [comment]
Ok thanks @igormcoelho :-)

I'll put through a revised version now - which hopefully preserves all of your intended message and also flows nicely in English - let me have a look...

**Comment by PBSJ** [comment]
Ok, so just had another attempt @igormcoelho , @vncoelho 

One of things that I think will help with readability is to be more explicit than implicit. 

For example, I think it's worth specifying 'blockchain literature' rather than just 'literature' as it's less ambiguous. 

Similarly sometimes a sentence will refer to 'it' or 'its'. And it can be quite tricky to understand what the 'it' refers to. So I have been more explicit here to make it easier for the reader to follow. 

Have a look now :-)

**Comment by vncoelho** [comment]
I will take a look with careful again, @PBSJ.

It should be "In the Literature", otherwise it is repetitive because we already use blockchain literature blockchain.
When when talk about "literature" it also requires "in the".

**Comment by vncoelho** [comment]
Please do not make any other change with upper case letters.

**Comment by vncoelho** [comment]
noteworthy is clear and is classical.

**Comment by vncoelho** [comment]
The phrase was again with wrong meaning commenting about append storage applications.

**Comment by vncoelho** [comment]
Thanks for the contributions.
I like the rewritten to this: "DApps utilising SCs tend to be more complex to develop and optimize when compared to DApps focused only on appending storage", congratulations! :dagger:

**Comment by PBSJ** [comment]
Thanks @vncoelho ! 

Can I ask what is meant by this sentence as I'm still struggling to understand it: 

>"Besides its significant advantages, satisfying this set of requirements poses additional constraints, vulnerabilities and challenges when compared to other consensus applications dealt in the literature."

What does 'its' in 'Besides its significant..." refer to here?

Also, which set of requirements are we referring to?

**Comment by vncoelho** [comment]
Everything mentioned in the current paragraph. But, bassically things, OBF and SMR.

**Comment by PBSJ** [comment]
Ok, I think I understand the message we're trying to convey - maybe I'll leave it for now and have a look through some more of the doc :-)

**Comment by vncoelho** [comment]
Do not  be shy, fell free to open more PRs...ahauaha

Thanks for the contributions.

If you want to open more you are welcomed. I think that small changes are easier for us to analyse and merge, as well as to track master's updates. Thus, better to split PRs.

**Comment by PBSJ** [comment]
Yes, thanks - I was liking your small changes.

I need to get more familiar with GitHub - it's the first time I've used it :-)

**Comment by vncoelho** [comment]
You are doing well. ;D
 We keep in touch. Time to back to sleep here,

**Comment by PBSJ** [comment]
Ay ay, it's late there haha. Still evening here in NZ. Have a good sleep

**Pull request merged**
